curso-flask/02-proyecto-flask/web-personal/app/projects/models.py
from app import db


class Project(db.Model):
    __tablename__ = "projects"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    description = db.Column(db.Text)
    github_url = db.Column(db.String(255))

    def __init__(self, title, description, github_url):
        self.title = title
        self.description = description
        self.github_url = github_url

    def __repr__(self):
        return f"<Project {self.title}>"

curso-flask/02-proyecto-flask/web-personal/app/__init__.py
from app.projects.views import project
from app.views import base
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

# configuration APP
app.config.from_object("config.DevelopmentConfig")

db = SQLAlchemy(app)

app.register_blueprint(base)
app.register_blueprint(project)
# from app import views

# create database and tables
with app.app_context():
    db.create_all()

curso-flask/02-proyecto-flask/web-personal/app/projects/views.py
from app import db
from app.projects.models import Project
from flask import Blueprint, redirect, render_template, request, url_for

project = Blueprint("project", __name__)


@project.route("/projects/index")
def index():
    projects = Project.query.all()
    db.session.commit()
    return render_template("project_templates/index.html", projects=projects)


@project.route("/projects/create")
def create():
    return render_template("project_templates/create.html")


@project.route("/projects/insert", methods=["POST"])
def insert():
    title = request.form.get("title")
    description = request.form.get("description")
    github_url = request.form.get("github_url")

    project = Project(title, description, github_url)
    db.session.add(project)
    db.session.commit()

    return redirect(url_for("project.index"))


@project.route("/projects/edit/<int:id>")
def edit(id):
    project = Project.query.get_or_404(id)
    return render_template("project_templates/edit.html", project=project)


@project.route("/projects/update/<int:id>", methods=["POST"])
def update(id):
    project = Project.query.get_or_404(id)
    project.title = request.form.get("title")
    project.description = request.form.get("description")
    project.github_url = request.form.get("github_url")

    db.session.add(project)
    db.session.commit()

    return redirect(url_for("project.index"))


@project.route("/projects/delete/<int:id>")
def delete(id):
    project = Project.query.get_or_404(id)
    db.session.delete(project)
    db.session.commit()

    return redirect(url_for("project.index"))

curso-flask/02-proyecto-flask/web-personal/app/views.py
from flask import Blueprint, render_template

# from app import app

base = Blueprint("base", __name__)


@base.route("/home")
def home():
    return render_template("home.html")


@base.route("/portfolio")
def portfolio():
    return render_template("portfolio.html")


@base.route("/contact")
def contact():
    return render_template("contact.html")

curso-flask/02-proyecto-flask/web-personal/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Darwin - {% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <a href="{{ url_for('base.home') }}">Inicio</a>
        <a href="{{ url_for('base.portfolio') }}">Porftolio</a>
        <a href="{{ url_for('base.contact') }}">Contacto</a>
    </header>

    {% block content %}

    {% endblock %}

    <footer>
        <p>&copy; 2024 Todos los derechos reservados - Darwin Ruiz - Diseño Web</p>
    </footer>
</body>
</html>

curso-flask/02-proyecto-flask/web-personal/app/templates/contact.html
{% extends 'base.html' %}

{% block title %} Contacto {% endblock %}

{% block content %} 
    <h1>Página de Contacto</h1>
{% endblock %}

curso-flask/02-proyecto-flask/web-personal/app/templates/home.html
{% extends 'base.html' %}

{% block title %} Inicio {% endblock %}

{% block content %} 
    <h1>Página de Inicio</h1>
{% endblock %}

curso-flask/02-proyecto-flask/web-personal/app/templates/portfolio.html
{% extends 'base.html' %}

{% block title %} Portfolio {% endblock %}

{% block content %} 
    <h1>Página de Portfolio</h1>
{% endblock %}

curso-flask/02-proyecto-flask/web-personal/app/templates/project_templates/create.html
{% extends './base.html' %}

{% block title %}Projects{% endblock %}

{% block content %}
    <h2>Insertar Proyecto</h2>

    <form action="{{ url_for('project.insert') }}" method="POST">
        <div>
            <label for="title">Titulo</label>
            <input type="text" id="title" name="title">
        </div>

        <div>
            <label for="description">Descripción</label> <br />
            <textarea id="description" name="description" cols="50" rows="10"></textarea>
        </div>

        <div>
            <label for="github_url">GitHub</label>
            <input type="url" id="github_url" name="github_url">
        </div>

        <div>
            <button type="submit">Insertar</button>
        </div>
    </form>
{% endblock %}

curso-flask/02-proyecto-flask/web-personal/app/templates/project_templates/edit.html
{% extends './base.html' %}

{% block title %}Projects{% endblock %}

{% block content %}
    <h2>Insertar Proyecto</h2>

    <form action="{{ url_for('project.update', id=project.id) }}" method="POST">
        <div>
            <label for="title">Titulo</label>
            <input type="text" id="title" name="title" value="{{ project.title }}">
        </div>

        <div>
            <label for="description">Descripción</label> <br />
            <textarea id="description" name="description" cols="50" rows="10">{{ project.description }}</textarea>
        </div>

        <div>
            <label for="github_url">GitHub</label>
            <input type="url" id="github_url" name="github_url" value="{{ project.github_url }}">
        </div>

        <div>
            <button type="submit">Actualizar</button>
        </div>
    </form>
{% endblock %}

curso-flask/02-proyecto-flask/web-personal/app/templates/project_templates/index.html
{% extends './base.html' %}

{% block title %}Projects{% endblock %}

{% block content %}
    <a href="{{ url_for('project.create') }}">Insertar un nuevo proyecto</a>
    <table>
        <tr>
            <th>Titulo</th>
            <th>Descripción</th>
            <th>Repositorio en GitHub</th>
        </tr>
        {% for project in projects %}
        <tr>
            <td>{{ project.title }}</td>
            <td>{{ project.description }}</td>
            <td><a href="{{ project.github_url }}" target="_blank">GitHub</a></td>
            <td><a href="{{ url_for('project.edit', id=project['id']) }}">Editar</a></td>
            <td><a href="{{ url_for('project.delete', id=project['id']) }}">Eliminar</a></td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}